# Generated by Django 4.1.3 on 2022-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'operation_add_name',
            },
        ),
        migrations.CreateModel(
            name='ApprovalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'operation_approval_name',
            },
        ),
        migrations.CreateModel(
            name='AudienceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'operation_audience_interest',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'operation_call_to_action',
            },
        ),
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'file_name',
            },
        ),
        migrations.CreateModel(
            name='ProductImageHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'operation_product_image_hash',
            },
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'operation_product_name',
            },
        ),
        migrations.CreateModel(
            name='StoryId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
            options={
                'db_table': 'operation_story_id',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=140)),
            ],
        ),
    ]
